site_name: Sentiment Analyzer
site_description: A FastAPI microservice for sentiment analysis
site_url: https://shreyaupretyy.github.io/sentiment-analyzer
repo_url: https://github.com/shreyaupretyy/sentiment-analyzer
repo_name: shreyaupretyy/sentiment-analyzer

theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - API Documentation: api.md
  - Deployment: deployment.md

plugins:
  - search
